/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package robertsonapplication;

/**
 *
 * @author ashba
 */
public class AddEditForm extends javax.swing.JDialog {
    ContactApp app;
    MainForm main;
    public int position;
    public boolean isEdit;
    /**
     * Creates new form AddEdotForm
     */
    public AddEditForm(ContactApp app, MainForm main) {
        this.app=app;
        this.main=main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fName = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        pNumber = new javax.swing.JLabel();
        eMail = new javax.swing.JLabel();
        fNameBox = new javax.swing.JTextField();
        EmailBox = new javax.swing.JTextField();
        lNameBox = new javax.swing.JTextField();
        pNumberBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fName.setText("First Name");

        lName.setText("Email");

        pNumber.setText("Last Name");

        eMail.setText("Phone Number");

        fNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameBoxActionPerformed(evt);
            }
        });

        EmailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailBoxActionPerformed(evt);
            }
        });

        lNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameBoxActionPerformed(evt);
            }
        });

        pNumberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNumberBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pNumber)
                        .addComponent(fName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lName)
                            .addComponent(eMail))
                        .addGap(2, 2, 2)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailBox)
                    .addComponent(pNumberBox)
                    .addComponent(lNameBox)
                    .addComponent(fNameBox))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fName)
                    .addComponent(fNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNumber)
                    .addComponent(lNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMail)
                    .addComponent(pNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(EmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        fNameBox.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameBoxActionPerformed
        // TO add your handling code here:
    }//GEN-LAST:event_fNameBoxActionPerformed

    private void lNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameBoxActionPerformed

    private void pNumberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNumberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNumberBoxActionPerformed

    private void EmailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (isEdit==true){
            app.editContact(fNameBox.getText(),lNameBox.getText(),pNumberBox.getText(),EmailBox.getText(), position);
            main.updateJList();
            main.refreshFields(position);
            this.dispose();
       
        }
        else {
            app.addContact(fNameBox.getText(),lNameBox.getText(),pNumberBox.getText(),EmailBox.getText());
            main.updateJList();
            main.refreshFields(app.getContactCount()-1);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    void setFields(String[]data){
        fNameBox.setText(data[0]);
        lNameBox.setText(data[1]);
        pNumberBox.setText(data[2]);
        EmailBox.setText(data[3]);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailBox;
    private javax.swing.JLabel eMail;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField fNameBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lName;
    private javax.swing.JTextField lNameBox;
    private javax.swing.JLabel pNumber;
    private javax.swing.JTextField pNumberBox;
    // End of variables declaration//GEN-END:variables
}
